---
title: "EDA Report"
author: "Group 4"
date: "2025-07-28"
output: html_document
---

```{r setup, include=FALSE}
#Loading in the necessary libraries (TD/AH).
library(tidyverse)
library(e1071)
library(corrplot)
```

```{r}
#Loading in the data sets (TD).

FYConsolidatedData = read.csv("h233.csv")
LongitudeData3Y = read.csv("h226.csv")
OfficeBasedVisits = read.csv("h229g.csv")
JobFile = read.csv("h227.csv")
load("NSDUH_2021.RData")
NSDUH = PUF2021_121323
```

```{r}
#Trimming FYConsolidatedData for usability (TD).

keeps <- c("DUPERSID","AGE21X", "SEX", "RACEV1X", "EDUCYR", "POVCAT21", "TTLP21X", "INSCOV21", "REGION21", "MNHLTH53","PERWT21F")

FYConsolidatedDataClean <- subset(FYConsolidatedData, select = keeps)

FYConsolidatedDataClean
```

```{r}
#Replacing numeric values with qualitative details FYConsolidatedDataClean (TD).

#Race (TD).
FYConsolidatedDataClean$RACEV1X[FYConsolidatedDataClean$RACEV1X == 1] <- 'White'
FYConsolidatedDataClean$RACEV1X[FYConsolidatedDataClean$RACEV1X == 2] <- 'Black'
FYConsolidatedDataClean$RACEV1X[FYConsolidatedDataClean$RACEV1X == 3] <- 'Amer Indian/Alaska Native'
FYConsolidatedDataClean$RACEV1X[FYConsolidatedDataClean$RACEV1X == 4] <- 'Asian/Natv Hawaiian/Pacfc Isl'
FYConsolidatedDataClean$RACEV1X[FYConsolidatedDataClean$RACEV1X == 6] <- 'Multiple Races Reported'

#Sex (TD).
FYConsolidatedDataClean$SEX[FYConsolidatedDataClean$SEX == 1] <- 'Male'
FYConsolidatedDataClean$SEX[FYConsolidatedDataClean$SEX == 2] <- 'Female'

#Categorical Poverty (TD).
FYConsolidatedDataClean$POVCAT21[FYConsolidatedDataClean$POVCAT21 == 1] <- 'Poor/Negative'
FYConsolidatedDataClean$POVCAT21[FYConsolidatedDataClean$POVCAT21 == 2] <- 'Near Poor'
FYConsolidatedDataClean$POVCAT21[FYConsolidatedDataClean$POVCAT21 == 3] <- 'Low Income'
FYConsolidatedDataClean$POVCAT21[FYConsolidatedDataClean$POVCAT21 == 4] <- 'Middle Income'
FYConsolidatedDataClean$POVCAT21[FYConsolidatedDataClean$POVCAT21 == 5] <- 'High Income'

#Education when first entering MEPS (TD).
FYConsolidatedDataClean$EDUCYR[FYConsolidatedDataClean$EDUCYR == 0] <- 'No School/Kindergarten'
FYConsolidatedDataClean$EDUCYR[FYConsolidatedDataClean$EDUCYR %in% 1:8] <- 'Elementary Grades'
FYConsolidatedDataClean$EDUCYR[FYConsolidatedDataClean$EDUCYR %in% 9:11] <- 'HighSchool Grades 9-11'
FYConsolidatedDataClean$EDUCYR[FYConsolidatedDataClean$EDUCYR == 12] <- 'Grade 12'
FYConsolidatedDataClean$EDUCYR[FYConsolidatedDataClean$EDUCYR == 13] <- '1 Year College'
FYConsolidatedDataClean$EDUCYR[FYConsolidatedDataClean$EDUCYR == 14] <- '2 Years College'
FYConsolidatedDataClean$EDUCYR[FYConsolidatedDataClean$EDUCYR == 15] <- '3 Years College'
FYConsolidatedDataClean$EDUCYR[FYConsolidatedDataClean$EDUCYR == 16] <- '4 Years College'
FYConsolidatedDataClean$EDUCYR[FYConsolidatedDataClean$EDUCYR == 17] <- '5+ Years College'

#Insurance Coverage (TD).
FYConsolidatedDataClean$INSCOV21[FYConsolidatedDataClean$INSCOV21 == 1] <- 'Any Private'
FYConsolidatedDataClean$INSCOV21[FYConsolidatedDataClean$INSCOV21 == 2] <- 'Public Only'
FYConsolidatedDataClean$INSCOV21[FYConsolidatedDataClean$INSCOV21 == 3] <- 'Uninsured'

#Census Location (As of 12/31/21) (TD).
FYConsolidatedDataClean$REGION21[FYConsolidatedDataClean$REGION21 == 1] <- 'NorthEast'
FYConsolidatedDataClean$REGION21[FYConsolidatedDataClean$REGION21 == 2] <- 'MidWest'
FYConsolidatedDataClean$REGION21[FYConsolidatedDataClean$REGION21 == 3] <- 'South'
FYConsolidatedDataClean$REGION21[FYConsolidatedDataClean$REGION21 == 4] <- 'West'

#Percieved Mental Health Status (As of Round 5/3) (Commenting these out for visual's sake) (TD).
#FYConsolidatedDataClean$MNHLTH53[FYConsolidatedDataClean$MNHLTH53 == 1] <- 'Excellent'
#FYConsolidatedDataClean$MNHLTH53[FYConsolidatedDataClean$MNHLTH53 == 2] <- 'Very Good'
#FYConsolidatedDataClean$MNHLTH53[FYConsolidatedDataClean$MNHLTH53 == 3] <- 'Good'
#FYConsolidatedDataClean$MNHLTH53[FYConsolidatedDataClean$MNHLTH53 == 4] <- 'Fair'
#FYConsolidatedDataClean$MNHLTH53[FYConsolidatedDataClean$MNHLTH53 == 5] <- 'Poor'

FYConsolidatedDataClean
```

``` {r}
#Trimming JobFile (TD).

keeps2 <- c("DUPERSID", "INDCODEX", "OCCCODEX", "EMPLINS")

JobFileJoining <- subset(JobFile, select = keeps2)

JobFileJoining
```

```{r}
#Replacing numeric values with qualitative details JobFileJoining (TD).

#Industry Code (TD).
JobFileJoining$INDCODEX[JobFileJoining$INDCODEX == -1] <- 'Inapplicapble'
JobFileJoining$INDCODEX[JobFileJoining$INDCODEX == 1] <- 'Natural Resources'
JobFileJoining$INDCODEX[JobFileJoining$INDCODEX == 2] <- 'Mining'
JobFileJoining$INDCODEX[JobFileJoining$INDCODEX == 3] <- 'Consrtuction'
JobFileJoining$INDCODEX[JobFileJoining$INDCODEX == 4] <- 'Manufacturing'
JobFileJoining$INDCODEX[JobFileJoining$INDCODEX == 5] <- 'Wholesale & Retail Trade'
JobFileJoining$INDCODEX[JobFileJoining$INDCODEX == 6] <- 'Transportation & Utilities'
JobFileJoining$INDCODEX[JobFileJoining$INDCODEX == 7] <- 'Information'
JobFileJoining$INDCODEX[JobFileJoining$INDCODEX == 8] <- 'Financial Activities'
JobFileJoining$INDCODEX[JobFileJoining$INDCODEX == 9] <- 'Professional & Business Services'
JobFileJoining$INDCODEX[JobFileJoining$INDCODEX == 10] <- 'Education, Health, & Social Services'
JobFileJoining$INDCODEX[JobFileJoining$INDCODEX == 11] <- 'Leisure & Hospitality'
JobFileJoining$INDCODEX[JobFileJoining$INDCODEX == 12] <- 'Other Services'
JobFileJoining$INDCODEX[JobFileJoining$INDCODEX == 13] <- 'Public Administration'
JobFileJoining$INDCODEX[JobFileJoining$INDCODEX == 14] <- 'Military'
JobFileJoining$INDCODEX[JobFileJoining$INDCODEX == 15] <- 'Unclassible Industry'

#Occupation Code (TD).
JobFileJoining$OCCCODEX[JobFileJoining$OCCCODEX == -1] <- 'Inapplicapble'
JobFileJoining$OCCCODEX[JobFileJoining$OCCCODEX == 1] <- 'Management, Business, & Financial Operations'
JobFileJoining$OCCCODEX[JobFileJoining$OCCCODEX == 2] <- 'Professional & Related Occupations'
JobFileJoining$OCCCODEX[JobFileJoining$OCCCODEX == 3] <- 'Service Occupations'
JobFileJoining$OCCCODEX[JobFileJoining$OCCCODEX == 4] <- 'Sales & Related Operations'
JobFileJoining$OCCCODEX[JobFileJoining$OCCCODEX == 5] <- 'Office & Administrative Support'
JobFileJoining$OCCCODEX[JobFileJoining$OCCCODEX == 6] <- 'Farming, Fishing, & Forestry'
JobFileJoining$OCCCODEX[JobFileJoining$OCCCODEX == 7] <- 'Construction, Extraction, & Maintenance'
JobFileJoining$OCCCODEX[JobFileJoining$OCCCODEX == 8] <- 'Production, Transportation, & Material Moving'
JobFileJoining$OCCCODEX[JobFileJoining$OCCCODEX == 9] <- 'Military Specific Occupations'
JobFileJoining$OCCCODEX[JobFileJoining$OCCCODEX == 11] <- 'Unclassible Occupation'

#Has Health Insurance through main job (TD).
JobFileJoining$EMPLINS[JobFileJoining$EMPLINS == -1] <- 'Inapplicapble'
JobFileJoining$EMPLINS[JobFileJoining$EMPLINS == 1] <- 'Yes'
JobFileJoining$EMPLINS[JobFileJoining$EMPLINS == 2] <- 'No'

JobFileJoining
```

```{r}
#Joining FYConsolidatedDataClean and JobFileJoining (TD).
FYJobInner <- merge(FYConsolidatedDataClean, JobFileJoining, by = "DUPERSID")

FYJobInner

FYJobLeft <- merge(FYConsolidatedDataClean, JobFileJoining, by = "DUPERSID", all.x = TRUE)

FYJobLeft
```

```{r}
#Trimming OfficeBasedVisits (TD).

keeps3 <- c("DUPERSID", "MEDPTYPE_M18", "VSTCTGRY", "DOCATLOC", "MEDPRESC")

OfficeBasedVisitsClean <- subset(OfficeBasedVisits, select = keeps3)

OfficeBasedVisitsClean
```

```{r}
#Replacing numeric values with qualitative details OfficeBasedVisitsClean (TD).

#Type of Med Person Patient Talked to on Visit (Only labeling the mental health ones. If someone can double check to make sure I didn't miss one that would be great) (TD).
OfficeBasedVisitsClean$MEDPTYPE_M18[OfficeBasedVisitsClean$MEDPTYPE_M18 == 6] <- 'Mental Health Cnslr/Marital or Fam Therapist'
OfficeBasedVisitsClean$MEDPTYPE_M18[OfficeBasedVisitsClean$MEDPTYPE_M18 == 13] <- 'Psychologist'
OfficeBasedVisitsClean$MEDPTYPE_M18[OfficeBasedVisitsClean$MEDPTYPE_M18 == 14] <- 'Social Worker'

#Visit Category (Only labeling the Mental health one) (TD).
OfficeBasedVisitsClean$VSTCTGRY[OfficeBasedVisitsClean$VSTCTGRY == 4] <- 'Psychotherapy/Mental Health Counsiling'

#Was there a MD at location where Patient saw the Provider? (TD).
OfficeBasedVisitsClean$DOCATLOC[OfficeBasedVisitsClean$DOCATLOC == 1] <- 'Yes'
OfficeBasedVisitsClean$DOCATLOC[OfficeBasedVisitsClean$DOCATLOC == 2] <- 'No'

#Medication Perscribed to Patient (TD).
OfficeBasedVisitsClean$MEDPRESC[OfficeBasedVisitsClean$MEDPRESC == 1] <- 'Yes'
OfficeBasedVisitsClean$MEDPRESC[OfficeBasedVisitsClean$MEDPRESC == 2] <- 'No'

OfficeBasedVisitsClean
```

```{r}
#Joining FYConsolidatedDataClean and OfficeBasedVisitsClean (TD).
FYOfficeInner <- merge(FYConsolidatedDataClean, OfficeBasedVisitsClean, by = "DUPERSID")

FYOfficeInner

FYOfficeLeft <- merge(FYConsolidatedDataClean, OfficeBasedVisitsClean, by = "DUPERSID", all.x = TRUE)

FYOfficeLeft
```

```{r}
#Range of Young Men Aged 18-25 visual (AH).
ggplot(FYConsolidatedDataClean %>% filter(SEX == 'Male' & AGE21X >= 18 & AGE21X <= 25), aes(x = AGE21X)) +
  geom_histogram(binwidth = 1, fill = "red", color = "white") +
  labs(title = "Range of Young Men Aged 18-25", x = "AGE", y = "Amount")
```

```{r}
#Young Men (18-25) Mental Health Status bar chart (AH).
ggplot(FYConsolidatedDataClean %>% filter(SEX == 'Male' & AGE21X >= 18 & AGE21X <= 25), aes(x = MNHLTH53)) +
  geom_bar(fill = "red", color = "black", alpha = 0.7) +
  labs(title = "Young Men (18-25) Mental Health Status", x = "Mental Health Status", y = "Amount")
```

```{r}
#Education vs Poverty Status Ages 18-25 visual (AH).
ggplot(FYConsolidatedDataClean %>% filter(SEX == 'Male' & AGE21X >= 18 & AGE21X <= 25 & EDUCYR > 0), aes(x = EDUCYR, fill = POVCAT21)) +
  geom_bar(position = "fill", color = "red") +
  labs(title = "Education vs Poverty Status Ages 18-25", x = "Level of Education", y = "Poverty Status") + 
  scale_fill_manual(values = c("lightgreen", "orange", "yellow", "green", "blue")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
#Average mean, median, and sd of mental health status per age (AH).
mean_mental_health_status <- FYConsolidatedDataClean %>% 
  group_by(AGE21X) %>% 
  summarise(
    mean_status = mean(MNHLTH53, na.rm = TRUE),
    median_status = median(MNHLTH53, na.rm = TRUE), 
    sd_status = sd(MNHLTH53, na.rm = TRUE)
  )

mean_mental_health_status_na <- mean_mental_health_status %>%
  filter(AGE21X != -1)

print(mean_mental_health_status_na)
```

```{r}
#Creating age brackets (AH).
FYConsolidatedDataClean$AGE_GROUP <- cut(FYConsolidatedDataClean$AGE21X,
                                         breaks = c(0, 10, 20, 30, 40, 50, 60, 70, 80, 90),
                                         labels = c("0-10", "11-20", "21-30", "31-40", "41-50", "51-60", "61-70", "71-80", "81-90"),
                                         right = FALSE)
```

```{r}
#Mean mental health status by age group (AH).
mean_mental_health_agegroup <- FYConsolidatedDataClean %>%
  filter(!is.na(MNHLTH53) & !is.na(AGE_GROUP)) %>%
  group_by(AGE_GROUP) %>%
  summarise(mean_status = mean(MNHLTH53, na.rm = TRUE))

head(mean_mental_health_agegroup)
```

```{r}
#Mean Mental Health Status by Age Group bar chart (AH).
ggplot(mean_mental_health_agegroup, aes(x = AGE_GROUP, y = mean_status)) +
  geom_bar(stat = "identity", fill = "lightgreen", color = "green", alpha = 0.7) +
  labs(title = "Mean Mental Health Status by Age Group", x = "Age", y = "Mental Health Status") + 
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
#Correlation matrix (AH).
numeric_variables <- FYConsolidatedDataClean %>%
  select(where(is.numeric))

correlation_matrix <- cor(numeric_variables, use = "complete.obs")

print(correlation_matrix)
```

```{r}
#Correlation matrix visual (AH).
corrplot(correlation_matrix, method = "circle",
         addCoef.col = "black")
```

```{r}
#Categorical variable table (AH).
cat_table <- FYConsolidatedDataClean %>%
  filter(!is.na(POVCAT21)) %>%
  count(POVCAT21) %>%
  mutate(percentage = n / sum(n) * 100)

cat_table
```

```{r}
#Continuous variable table involving skewness, kurtosis, sd, median, mean, minimum and maximum (AH).

con_table <- FYConsolidatedDataClean %>%
  filter(!is.na(MNHLTH53)) %>%
  summarise(
    Skewness_MNHLTH53 = skewness(MNHLTH53, na.rm = TRUE),
    Kurtosis_MNHLTH53 = kurtosis(MNHLTH53, na.rm = TRUE),
    Sd_MNHLTH53 = sd(MNHLTH53, na.rm = TRUE),
    Median_MNHLTH53 = median(MNHLTH53, na.rm = TRUE),
    Mean_MNHLTH53 = mean(MNHLTH53, na.rm = TRUE),
    Min_MNHLTH53 = min(MNHLTH53, na.rm = TRUE),
    Max_MNHLTH53 = max(MNHLTH53, na.rm = TRUE),
  )

con_table
```

```{r}
#Making a varaible that counts the ammount of recorded visits to Psychotherapy/Mental Health Counciling by individual ID (TD).

Counciling <- FYOfficeLeft %>% filter(VSTCTGRY == 'Psychotherapy/Mental Health Counsiling')

CouncilingCount <- plyr::count(Counciling$DUPERSID)

colnames(CouncilingCount) <- c("DUPERSID", "MentalHealthAppointments")

FYCouncilingLeft <- merge(FYConsolidatedDataClean, CouncilingCount, by = "DUPERSID", all.x = TRUE)

FYCouncilingLeft$MentalHealthAppointments[is.na(FYCouncilingLeft$MentalHealthAppointments)] <- 0

#Made a small table for the count of recorded Visits (TD).

VisitTable <- plyr::count(FYCouncilingLeft$MentalHealthAppointments)

colnames(VisitTable) <- c("MentalHealthAppointments", "Frequency")

VisitTable
```

```{r}
#Made a jitter plot to try and visualize frequency of visits to mental health status. Too little variables within the 18-25 range and skewed towards the lower end made the graph not turn out well. (TD).

ggplot(FYCouncilingLeft %>% filter(SEX == 'Male' & AGE21X >= 18 & AGE21X <= 25 & MNHLTH53 > 0 & MentalHealthAppointments > 0), aes(x = MNHLTH53, y = MentalHealthAppointments)) +
  geom_jitter(position = "jitter") +
  labs(title = "Young Men (18-25) Mental Health Status", x = "Mental Health Status", y = "Amount")
```

```{r}
# Therapy Attending Young Men (18-25) Mental Health Status bar chart (TD).
ggplot(FYCouncilingLeft %>% filter(SEX == 'Male' & AGE21X >= 18 & AGE21X <= 25 & MNHLTH53 > 0 & MentalHealthAppointments > 0), aes(x = MNHLTH53)) +
  geom_bar(fill = "red", color = "black", alpha = 0.7) +
  labs(title = "Therapy Attending Young Men (18-25) Mental Health Status", x = "Mental Health Status", y = "Amount")
```

```{r}
# Therapy Attending Individuals Mental Health Status bar chart (TD).
ggplot(FYCouncilingLeft %>% filter(MNHLTH53 > 0 & MentalHealthAppointments > 0), aes(x = MNHLTH53)) +
  geom_bar(fill = "red", color = "black", alpha = 0.7) +
  labs(title = "Therapy Attending Individuals Mental Health Status", x = "Mental Health Status", y = "Amount")
```

```{r}
#Filtering out the missing values (TD/AH).
FYCouncilingNA <- FYCouncilingLeft %>%
  filter(
    EDUCYR > 0,
    MNHLTH53 > 0,
    SEX > 0,
    REGION21 > 0,
    POVCAT21 > 0,
    INSCOV21> 0
  )
```

```{r}
#Splitting Training and Test Sets. (Specifically Counseling Join) (TD).

FYCouncilingSize <- floor(.75*nrow(FYCouncilingNA))

set.seed(69420)

train <- sample(seq_len(nrow(FYCouncilingNA)), size = FYCouncilingSize)

FYCouncilingTrain <- FYCouncilingNA[train, ]
FYCouncilingTest <- FYCouncilingNA[-train, ]
FYCouncilingTestMental <- FYCouncilingNA$MNHLTH53[-train]
```

```{r}
#(TD).
FYCouncilingGLM <- glm(MNHLTH53 ~ .,
                        data = FYCouncilingNA, subset = train)

summary(FYCouncilingGLM)
```

```{r}
#LDA on FYCounciling (TD/AH)

require(MASS)

FYCouncilingLDA <- lda(MNHLTH53 ~ . - EDUCYR,
                       data = FYCouncilingNA, subset = train)

FYCouncilingLDA
```

```{r}
#Using LDA as a Predictor (TD).

FYCouncilingLDAPredict <- predict(FYCouncilingLDA, FYCouncilingTest)

#names(FYCouncilingLDAPredict)

table(FYCouncilingLDAPredict$class, FYCouncilingTestMental)

#Now that the LDA is set up, we should really think about what to do with the missing data (TD).
```
